name: Builder Core

on: workflow_dispatch

jobs:
  build-core:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: 
          - macos-latest
          - windows-latest
        host:
          - x64
        node: 
          - 12
        include: 
          - os: windows-latest
            node: 12
            host: x86
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init and Update submodules
        run: |
          git submodule init
          git submodule update

      - name: Clone build_tools
        run: |
          git clone https://github.com/kanweiwei/build_tools
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          dir: ${{ github.workspace }}/example/
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install grunt
        run: npm install grunt -g

      - name: Build core
        run: |
          cd build_tools/
          python3 ./configure.py --update=0 --module=core --platform=native --qt-dir=${{ github.workspace }}/example/Qt/5.15.2 --no-apps=1
          python3 ./make.py

      - name: ${{ matrix.os }}_${{ matrix.host }}_artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: build_tools/out
          if-no-files-found: error
          
        
