name: Build Core

on: workflow_dispatch

jobs:
  build-core:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: 
          - windows-2019
        host:
          - x64
        node: 
          - 12
        include: 
          - os: windows-2019
            node: 12
            host: x86
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init and Update submodules
        run: |
          git submodule update --init --recursive

      - name: Clone build_tools
        run: |
          git clone https://github.com/kanweiwei/build_tools
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          dir: ${{ github.workspace }}/example/
      
      - name: Install grunt
        run: npm install grunt -g --force

      - name: Add Windows Kits to PATH
        if: runner.os == 'Windows'
        uses: myci-actions/append-to-path-windows@2
        with:
          path: C:\Program Files (x86)\Windows Kits\10\Extension SDKs\WindowsDesktop\10.0.20348.0\x64

      - name: Build core
        if: matrix.os != 'windows-2019'
        run: |
          cd build_tools/
          python3 ./configure.py --update=0 --module=core --platform=native --qt-dir=${{ github.workspace }}/example/Qt/5.15.2 --no-apps=1
          python3 ./make.py
      
      - name: Build core on Windows
        if: matrix.os == 'windows-2019'
        env:
          DEPOT_TOOLS_WIN_TOOLCHAIN: 0
          GYP_MSVS_VERSION: 2017
          GYP_CHROMIUM_NO_ACTION: 0
        run: |
          cd build_tools/
          python3 ./configure.py --update=0 --module=core --platform=native --qt-dir=${{ github.workspace }}/example/Qt/5.15.2 --no-apps=1
          python3 ./make.py

      - name: Upload ${{ matrix.os }}_${{ matrix.host }}_artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: build_tools/out
          if-no-files-found: error
          retention-days: 5
          
        
